from pathlib import Path

PROJECT_NAME = "ARCS-CRYPTO"
MAGIC = 20260418

BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
LOGS_DIR = BASE_DIR / "logs"
ARCHIVE_DIR = LOGS_DIR / "archive"
DASHBOARD_DIR = BASE_DIR / "dashboard"

DB_PATH = DATA_DIR / "crypto_trades.db"
STATUS_PATH = DATA_DIR / "bot_status.json"
RUNTIME_LOG = LOGS_DIR / "crypto_weekend.log"
TRADING_LOG = LOGS_DIR / "crypto_trading.log"

LOOP_INTERVAL_S = 15
REFRESH_INTERVAL_S = 15

TF_H1 = "H1"
TF_M15 = "M15"
TF_M1 = "M1"

CANDLES_H1 = 320
CANDLES_M15 = 320
CANDLES_M1 = 360

PAIRS = [
    "BTCUSD",
    "ETHUSD",
    "SOLUSD",
    "XRPUSD",
    "LTCUSD",
    "DOGEUSD",
]

PRICE_UNITS = {
    "BTCUSD": 1.0,
    "ETHUSD": 0.1,
    "SOLUSD": 0.01,
    "XRPUSD": 0.0001,
    "LTCUSD": 0.01,
    "DOGEUSD": 0.0001,
}

SPREAD_LIMITS_UNITS = {
    "BTCUSD": 90.0,
    "ETHUSD": 70.0,
    "SOLUSD": 75.0,
    "XRPUSD": 200.0,
    "LTCUSD": 150.0,
    "DOGEUSD": 120.0,
}

RISK_PER_TRADE_PCT = 0.08
MAX_RISK_PCT = 0.15
MAX_OPEN_TRADES = 1
MAX_OPEN_PER_SYMBOL = 1

BREAKEVEN_TRIGGER_R = 0.30
PARTIAL_TRIGGER_R = 0.55
TRAIL_TRIGGER_R = 0.85
TRAIL_RATIO = 0.55
TIME_STOP_MIN = 12

MICRO_BREAKEVEN_TRIGGER_R = 0.25
MICRO_PARTIAL_TRIGGER_R = 0.45
MICRO_TRAIL_TRIGGER_R = 0.65
MICRO_TIME_STOP_MIN = 8

TREND_ADX_MIN = 18.0
H1_RANGE_ADX_MAX = 24.0
M15_RANGE_LOOKBACK = 24
M1_SWEEP_LOOKBACK = 20
M1_BREAKOUT_LOOKBACK = 12

MIN_CONFIDENCE = 64.0

MAX_SESSION_DRAWDOWN_PCT = 3.0
MAX_CONSECUTIVE_LOSSES = 2
LOSS_COOLDOWN_MIN = 45
SYMBOL_REENTRY_COOLDOWN_MIN = 20

WEB_HOST = "127.0.0.1"
WEB_PORT = 5050
